title: My GitHub Pages Site  # Replace with your site's name
description: A description of my site  # A short tagline or description
author: Your Name  # Replace with your name
theme: minima  # Default theme provided by GitHub Pages
url: https://example.com  # Replace with your site's URL
baseurl: ""  # Leave empty for the root, or specify subdirectory (e.g., /blog)
social_links:
  twitter: your_twitter_handle
  github: your_github_username
  linkedin: your_linkedin_profile
